void main() 

{
   //Program demonstrating Conditional operations 
 
  var a = 11;
  
 var b =  a == 11 ? true : false;
   print(b) ;
   //Program demonstrating Cascade Notation Index Operator
  var myList = []
    ..add(1)
    ..add(2)
    ..add(3)
    ..add(4);

  print(myList); 

//Program demonstrating Index Operator
  
 // Accessing Elements in a List ([])
  var ages = [10, 20, 30, 40];
  
  // Accessing the second element (index 1)
  print(ages[1]); 

//  Modifying Elements in a List ([]=)
  
 
  var num = [10, 20, 30, 40];
  
  // Updating the second element (index 1)
  num[1] = 50;
  
  print(num); 


  }

